Update 05-trust-contracts.md
bosagora/docs-bosagora-io pull request #10
Opened 2021-07-14 15:13 UTC by cjweisman

Fixed header typo. Completed the section

2021-07-14 16:31 UTC, kchulj commented
Thank you for the prompt update. Brian and I will have a better look at it tomorrow.

Fixes #9

2021-07-14 22:03 UTC, hewison-chris requested changes
A couple of typos.

2021-07-14 22:03 UTC, hewison-chris commented on docs/source/05-trust-contracts.md
> +The ultimate goal of this architecture is to enble users to build a dedecidable contract, which ensures safe and accurate execution, while maximizing its scalability.
```suggestion
The ultimate goal of this architecture is to enable users to build a decidable contract, which ensures safe and accurate execution, while maximizing its scalability.
```

2021-07-15 04:42 UTC, kchulj commented
Ping @bpalaggi for review

2021-07-15 07:17 UTC, kchulj approved these changes
LGTM
Thank you @hewison-chris

2021-07-15 07:38 UTC, bpalaggi commented
LGTM thanks @kchulj @cjweisman

2021-07-15 07:49 UTC, bpalaggi approved these changes

2021-07-15 13:37 UTC, merged

2021-07-15 22:05 UTC, hewison-chris commented on docs/source/05-trust-contracts.md
> +The ultimate goal of this architecture is to enble users to build a dedecidable contract, which ensures safe and accurate execution, while maximizing its scalability.
Looks like this suggestion was not applied to fix the typos.