Add web wallet's Korean documentation
bosagora/docs-bosagora-io pull request #24
Opened 2021-12-14 05:34 UTC by MichaelKim20

I add Korean documentation for the web wallet.

### Installation of MKDocs
https://www.mkdocs.org/user-guide/installation/#installing-mkdocs

### Preview:
```
mkdocs serve
```

### Build:
```
mkdocs build
```

### Result:
[site.zip](https://github.com/bosagora/docs-bosagora-io/files/7708956/site.zip)

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/01-wallet-guide.md
> +계정 주소는 자유롭게 공유하고 표시할 수 있습니다 .
```suggestion
계정 주소는 자유롭게 공유하고 표시할 수 있습니다. 
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/01-wallet-guide.md
> +계정의 비밀키를 분실하면 해당 계정 주소로 전송된 모든 코인이 영구적으로 손실됩니다 .
```suggestion
계정의 비밀키를 분실하면 해당 계정 주소로 전송된 모든 코인이 영구적으로 손실됩니다.
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/01-introduction.md
> +사용자가 브라우즈를 닫거나, 다른 사이트로 이동했을 때, 월렛에 등록된 비밀키는 모두 제거됩니다.
```suggestion
사용자가 웹 브라우저를 닫거나, 다른 사이트로 이동했을 때, 월렛에 등록된 비밀키는 모두 제거됩니다. 
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/01-introduction.md
> +블록체인에 저장된 트랜잭션은 완료되었으며 변경될 수 없습니다.
```suggestion
블록외부화로 블록에 포함된 트랜잭션은 변경될 수 없습니다.
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/01-introduction.md
> +높음에 해당하는 수수료로 설정된 트랜잭션은 빠른 시간안에 블록체인에 저장되고, 낮음에 해당하는 수수료로 설정된 트랜잭션은 늦게 블록체인에 저장될 것입니다.
```suggestion
높음에 해당하는 수수료로 설정된 트랜잭션은 빠른 시간안에 블록에 포함되고, 낮음에 해당하는 수수료로 설정된 트랜잭션은 늦게 블록에 포함될 것입니다.
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/02-getting-started.md
> +공개키는 계정에 반드시 등록되어 있지만 비밀키는 등록되어 있지 않을 수 있습니다. 비밀키가 등록된 계정의 모드는 Sudo입니다. 그렇지 않은 계정의 모드는 ReadOnly입니다. 그리고 웹 월렛은 Sudo의 갯수를 숫자를 표시하기  때문에 사용자가 현재 월렛에 등록된 비밀키의 갯수를 쉽게 파악할 수 있게 해줍니다.
```suggestion
공개키는 계정에 반드시 등록되어 있지만 비밀키는 등록되어 있지 않을 수 있습니다. 비밀키가 등록된 계정의 모드는 Sudo입니다. 그렇지 않은 계정의 모드는 ReadOnly입니다. 그리고 웹 월렛은 Sudo의 갯수를 숫자를 표시하기 때문에 사용자가 현재 월렛에 등록된 비밀키의 갯수를 쉽게 파악할 수 있게 해줍니다.
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/02-getting-started.md
> +필드로는 트랜잭션유형, 시간, 금액, 상대방 주소가 있습니다.
```suggestion
표시항목으로는 트랜잭션유형, 시간, 금액, 상대방 주소가 있습니다. 
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/02-getting-started.md
> +* 금액은 전송된 자금의 양입니다.
```suggestion
* 금액은 전송된 자금의 양 입니다.
```

2021-12-14 06:27 UTC, TrustHenry commented on docs/wallet/web/03-how-to.md
> +그리고 복사된 키를 별도의 저장소에 저장하여야 합니다. 다른 곳에서는 비밀키를 보여주는 곳이 없기 때문에 이 곳에서 반드시 다른 곳에 저장하여 두어야 합니다. 그리고 아래쪽 체크박스를 클릭합니다.
```suggestion
그리고 복사된 키를 별도의 저장소에 저장하여야 합니다. 다른 곳에서는 비밀키를 보여주는 곳이 없기 때문에 이 곳에서 반드시 다른 곳에 저장(백업)해야 합니다. 그리고 아래쪽 체크박스를 클릭합니다.
```

2021-12-14 06:27 UTC, TrustHenry commented on mkdocs.yml
> +    - BOA 월렛 가이드: ./wallet/01-wallet-guide.md
```suggestion
    - BOSAGORA 월렛 가이드: ./wallet/01-wallet-guide.md
```

2021-12-14 08:30 UTC, MichaelKim20 commented on docs/wallet/web/01-introduction.md
> +블록체인에 저장된 트랜잭션은 완료되었으며 변경될 수 없습니다.
블록체인에 저장된 블록은 외부화된 블록으로 볼수 있기 때문에 기존 문구를 유지 하도록 하겠습니다.

2021-12-15 01:22 UTC, TrustHenry approved these changes
LGTM

2021-12-15 06:23 UTC, Kang-Simon requested changes

2021-12-15 06:23 UTC, Kang-Simon commented on docs/wallet/web/01-introduction.md
> +따라서 사용자는 별도의 키입력 없이 잔고조회와 트랜잭션의 내역을 조회할 수 있습니다.
```suggestion
따라서 사용자는 별도의 키입력 없이 기존에 등록된 계정으로 잔고조회와 트랜잭션의 내역을 조회할 수 있습니다. 
```

2021-12-15 06:23 UTC, Kang-Simon commented on docs/wallet/web/03-how-to.md
> +CoinNet과 TestNet 중 하나를 선택할 수 있습니다.
네트워크 중 하나를 선택하는것은 상단바에서 제공하고 있으며 설정의  Endpoints는 CoinNet과 TestNet을 선택하는 기능이 아닌 해당 네트워크의 접속 주소를 확인 및 변경하는 기능으로 작동합니다.

2021-12-15 06:56 UTC, Kang-Simon approved these changes
LGTM

2021-12-15 08:04 UTC, merged